export {default as BigTextBox} from './bigTextBox/BigText'
export {default as SmallTextBox} from './smallTextBox/SmallText'
export {default as AboutTable} from './aboutTable/AboutTable'
export {default as LeftAlignedTextBox} from './leftAlignedTextBox/LeftAlignedText'
export {default as VideoDiv} from './videoBackground/VideoBackground'
export {default as DescriptionBox} from './descriptionBox/DescriptionBox'